M48
; DRILL file {KiCad (6.0.5)} date Wed May 17 00:43:46 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-05-17T00:43:46-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.1260
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T2C0.2165
%
G90
G05
T1
X2.45Y-1.3
X2.45Y-6.15
X3.25Y-1.3
X3.25Y-6.15
T2
X2.6Y-3.75
X2.6Y-4.3
X2.6Y-4.85
X2.6Y-5.4
X2.85Y-2.25
X2.85Y-3.0
X3.1Y-3.75
X3.1Y-4.3
X3.1Y-4.85
X3.1Y-5.4
T0
M30
